version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      # Install the latest stable PlatformIO
      - restore_cache:
          key: platformio
      - run: sudo pip install -U platformio
      - run: "cd firmware ; platformio update"
      - run: "for file in firmware/include/*_example.h ; do cp $file ${file%%_example.h}.h ; done "
      - run: "cd firmware ; platformio run -e mkrwifi1010 -e nano_33_iot -e esp"

      - save_cache:
          key: platformio
          paths:
            - "../.platformio"
