version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      # Install the latest stable PlatformIO
      - restore_cache:
          key: platformio
      - run: sudo pip install -U platformio
      - run: "cd firmware ; platformio update"
      - run: "cp firmware/include/wifi_client_secrets_example.h firmware/include/wifi_client_secrets.h"
      - run: "cp firmware/include/aws_iot_secrets_example.h firmware/include/aws_iot_secrets.h"
      - run: "cd firmware ; platformio run -e mkrwifi1010 -e nano_33_iot -e esp"

      - save_cache:
          key: platformio
          paths:
            - "../.platformio"
