/*
 * Siedle In-Home bus frame format, hardware independent.
 *
 * A frame is 32 bits, transmitted MSB first with a fixed bit time of 2 ms. A logical 1 is the idle bus level
 * (high, ~28 V), a logical 0 pulls the bus low. Bit 31 is always 0, so every frame starts with a falling edge.
 *
 * Field layout (bit 31 = MSB), see also lambda/siedle-lib.js:
 *
 *   31..29  fixed 0b010
 *   28..25  signal (ring, door open, ...)
 *   24..23  unknown (usually 0b00)
 *   22..14  destination address
 *   13..11  fixed 0b010
 *   10..2   source address
 *    1..0   unknown (usually 0b00)
 *
 * This component has no ESP-IDF dependencies so it can be unit tested on the host (see test/host).
 */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SIEDLE_FRAME_BITS 32
#define SIEDLE_BIT_US     2000

typedef uint32_t siedle_cmd_t;

/** Known signal values, taken from lambda/siedle.json */
typedef enum {
    SIEDLE_SIGNAL_TALK_START = 0,  /**< handset off hook, speech channel opened */
    SIEDLE_SIGNAL_RING = 2,
    SIEDLE_SIGNAL_DOOR_OPEN = 3,
    SIEDLE_SIGNAL_TALK_END = 8,    /**< handset on hook */
    SIEDLE_SIGNAL_LIGHT = 11,
    SIEDLE_SIGNAL_RING_ALT = 12,
} siedle_signal_t;

uint8_t siedle_cmd_signal(siedle_cmd_t cmd);
uint16_t siedle_cmd_dst(siedle_cmd_t cmd);
uint16_t siedle_cmd_src(siedle_cmd_t cmd);

/** Build a command the same way lambda/siedle-lib.js getCmd() does. */
siedle_cmd_t siedle_cmd_make(uint8_t signal, uint16_t src, uint16_t dst);

/** Human readable signal name, or NULL if unknown. */
const char *siedle_signal_name(uint8_t signal);

/** A run of constant bus level, as captured or generated by e.g. the RMT peripheral. */
typedef struct {
    uint8_t level;        /**< 0 = bus pulled low, 1 = bus high (idle) */
    uint32_t duration_us; /**< 0 marks an open ended run, e.g. the bus going idle at the end of a frame */
} siedle_run_t;

/**
 * Encode a command into runs of constant level, merging consecutive equal bits.
 *
 * @return number of runs written (at most SIEDLE_FRAME_BITS), 0 if max_runs is too small
 */
size_t siedle_encode_runs(siedle_cmd_t cmd, uint32_t bit_us, siedle_run_t *runs, size_t max_runs);

typedef enum {
    SIEDLE_DECODE_OK = 0,
    SIEDLE_DECODE_NO_START,   /**< first run is not a low level */
    SIEDLE_DECODE_GLITCH,     /**< a run is shorter than half a bit */
    SIEDLE_DECODE_TRUNCATED,  /**< frame ended while the bus was still pulled low */
} siedle_decode_result_t;

/**
 * Decode runs of constant level (starting at the falling start edge) into a command.
 *
 * Each run is rounded to the nearest number of bit times. Missing trailing bits are taken as 1 (idle level),
 * surplus bits are ignored since the final high run merges with the idle bus.
 */
siedle_decode_result_t siedle_decode_runs(const siedle_run_t *runs, size_t num_runs, uint32_t bit_us,
                                          siedle_cmd_t *out_cmd);

#ifdef __cplusplus
}
#endif
